EMAIL_MAX_LENGTH = 254
USERNAME_MAX_LENGTH = 150
NAME_MAX_LENGTH = 150
USERNAME_PATTERN = r'^[\w.@+-]+\Z'

TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32

PRODUCT_NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256
MIN_COOKING_TIME = 1
MIN_PRODUCT_AMOUNT = 1
